### ISSUE TITLE
Install success but can't use with Error: spawn ENOENT

### ISSUE THREAD

**Issue by hoangddt** [bevacqua/hit-that#3]
Hello, I just installed with this command

```
sudo npm install -g hit-that
```

And the terminal show it

``` sh
  % sudo npm install -g hit-that                                                                                 !1848

> phantomjs@1.9.16 install /usr/lib/node_modules/hit-that/node_modules/webshot/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /usr/lib/node_modules/hit-that/node_modules/webshot/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [=====-----------------------------------] 13% 0.0s
Error making request.
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional dep failed, continuing phantomjs@1.9.16
/usr/bin/ht -> /usr/lib/node_modules/hit-that/cli.js
hit-that@1.0.0 /usr/lib/node_modules/hit-that
├── minimist@1.1.1
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── picture-tube@0.0.4 (x256@0.0.2, buffers@0.1.1, charm@0.1.2, request@2.9.203, png-js@0.1.1, event-stream@0.9.8, optimist@0.3.7)
└── webshot@0.15.4 (graceful-fs@3.0.6, tmp@0.0.25, cross-spawn@0.2.9)

```

Then, I check by run:

``` sh
  % ht --help                                                                                                    !1851

  Hit an HTML page and render it in your terminal

  Usage:

  ht <url> --width [width] --height [height] --cols [cols]

  Options:

    -w --width   Viewport width in pixels
    -h --height  Viewport height in pixels
    -c --cols    Terminal columns to use
    -h --help    Render this information
    -v --version Render version information

```

But when I use, it caught an error

``` sh
 % ht ponyfoo.com                                                                                               !1850

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

```

**Comment by bevacqua** [comment]
See phantomjs troubleshooting page
